name: Build and Push Frontend

on:
  workflow_call:
  push:
    branches: [ master ]
    paths:
      - 'frontend/**'
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4  

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Cache Docker Image Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-frontend-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-frontend-buildx-

      - name: Build and Push Frontend Image
        id: build_frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Verify Frontend Build Digest
        run: |
          echo "Frontend Image Digest: ${{ steps.build_frontend.outputs.digest }}"
